# Generated by Django 2.0.7 on 2018-07-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionindexpage',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='sectionpage',
            name='section_page_title',
        ),
    ]
