# Generated by Django 2.0.7 on 2018-07-22 11:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('section', '0005_sectiontagindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'Section categories',
            },
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='section.SectionCategory'),
        ),
    ]
