# Generated by Django 2.0.7 on 2018-07-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('section', '0006_auto_20180722_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionindexpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
