# Generated by Django 2.0.7 on 2018-07-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_sectionindexpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionindexpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
