# Generated by Django 2.0.3 on 2018-07-29 16:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_auto_20180722_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncategory',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descrizione della sezione'),
        ),
    ]
