# Generated by Django 2.0.3 on 2018-07-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0009_sectioncategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioncategory',
            old_name='description',
            new_name='section_description',
        ),
    ]
