# Generated by Django 2.0.3 on 2018-07-29 17:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0010_auto_20180729_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncategory',
            name='section_description',
        ),
        migrations.AddField(
            model_name='sectionindexpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descrizione della sezione'),
        ),
    ]
