# Generated by Django 2.0.7 on 2018-07-22 10:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
