# Generated by Django 2.0.7 on 2018-07-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
