# Generated by Django 2.0.3 on 2018-08-19 10:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_related_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_page',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='related_link',
            field=wagtail.core.fields.StreamField([('rel_page', wagtail.core.blocks.PageChooserBlock('section.SectionIndexPage'))], blank=True),
        ),
    ]
